### ISSUE TITLE
When other players crouch, host will also crouch.

### ISSUE THREAD

**Issue by SengeeSama** [chyzman/getdown#1]
I play on LAN multiplayer with my friend and whenever he crawls, my character will also crawl, which is beyond annoying. I don't know how this is possible but somehow the crawling is not local.
Side-note: His character will not crawl when I (the LAN host) crawls. Only the other way around.

**Comment by chyzman** [comment]
which of you guys are using toggle/hold?

**Comment by SengeeSama** [comment]
Me, the host, is using toggle. Friend is probably using hold (if that's default, I'm certain whatever is default is what he's using), can't confirm now.

**Comment by chyzman** [comment]
try the latest version (1.1.1), also toggle is default

**Comment by Yuta12342** [comment]
> try the latest version (1.1.1), also toggle is default

Meep. For me, we are both using the default (Toggle), and it does in fact force the host to crouch (using 1.1.1, on 1.21.1).
